// completed component from roller folder

import * as React from 'react';
import { RollerDisplay } from './roller/roller-display-component';
import { RollerButton } from './roller/roller-button-component';

export class dieRollerComponent extends React.Component<any, any> {

    constructor(props: any) { // make the roller, set first number to 0
        super(props);
        this.state = {
            result: 0
        }
    }

    randomize(value: number) { // randomize function, takes in a number and sets it equal to it. Number generated by sub component
        this.setState({
            result: value
        });
    }

    render() { //make the thing
        return (
            <div>
                {/* <div>{this.state.clicks}</div> */}
                <RollerDisplay result={this.state.result /* pass in result to Roller*/} />
                <RollerButton
                    randomize={(x: number) => this.randomize(x) /* function to pass child's randomizer up to parent*/}
                    result={this.state.result /* pass in result to button*/} />
                {/* <ClickerButton increment={this.increment.bind(this)} /> */}
            </div>
        )
    }
}